-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema G4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema G4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `G4` DEFAULT CHARACTER SET utf8 ;
USE `G4` ;

-- -----------------------------------------------------
-- Table `G4`.`MEMBER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G4`.`MEMBER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACCOUNT` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `PHONE` CHAR(10) NOT NULL,
  `DATE` DATE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G4`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G4`.`ORDER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `INVOICE` VARCHAR(45) NOT NULL,
  `ACCOUNT` VARCHAR(45) NOT NULL,
  `ORDER_STATUS` BIT(1) NOT NULL,
  `ORDER_DATE` DATE NOT NULL,
  `DISCOUNT_CODE` VARCHAR(45) NOT NULL,
  `DISCOUNT_TOTAL` VARCHAR(45) NOT NULL,
  `MEMBER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_ORDER_MEMBER_ID_idx` (`MEMBER_ID` ASC) VISIBLE,
  CONSTRAINT `FK_ORDER_MEMBER_ID`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `G4`.`MEMBER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G4`.`EXHIBITION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G4`.`EXHIBITION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EXHIBITION_STYLE` VARCHAR(45) NOT NULL,
  `EXHIBITION_PIC` VARCHAR(45) NOT NULL,
  `EXHIBITION_STATUS` VARCHAR(45) NOT NULL,
  `EXHIBITION_DATE` DATE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G4`.`EVENT_DETAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G4`.`EVENT_DETAIL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EVENT_NAME` VARCHAR(45) NOT NULL,
  `EVENT_BEGIN` DATE NOT NULL,
  `EVENT_END` DATE NOT NULL,
  `EXHIBITION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_EVENT_DETAIL_EXHIBITION_ID_idx` (`EXHIBITION_ID` ASC) VISIBLE,
  CONSTRAINT `FK_EVENT_DETAIL_EXHIBITION_ID`
    FOREIGN KEY (`EXHIBITION_ID`)
    REFERENCES `G4`.`EXHIBITION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G4`.`TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G4`.`TICKET` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TICKET_TYPE` VARCHAR(45) NOT NULL,
  `TICKET_PRICE` VARCHAR(45) NOT NULL,
  `TICKET_TOTAL` VARCHAR(45) NOT NULL,
  `TICKET_STATUS` VARCHAR(45) NOT NULL,
  `TICKET_DATE` DATE NOT NULL,
  `ORDER_ID` INT NOT NULL,
  `EVENT_DETAIL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_TICKET_ORDER_ID_idx` (`ORDER_ID` ASC) VISIBLE,
  INDEX `FK_TICKET_EVENT_DETAIL_ID_idx` (`EVENT_DETAIL_ID` ASC) VISIBLE,
  CONSTRAINT `FK_TICKET_ORDER_ID`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `G4`.`ORDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TICKET_EVENT_DETAIL_ID`
    FOREIGN KEY (`EVENT_DETAIL_ID`)
    REFERENCES `G4`.`EVENT_DETAIL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G4`.`NEWS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G4`.`NEWS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NEWS_NAME` VARCHAR(45) NOT NULL,
  `NEWS_PIC` VARCHAR(45) NOT NULL,
  `NEWS_CONTENT` VARCHAR(45) NOT NULL,
  `NEWS_STATUS` VARCHAR(45) NOT NULL,
  `NEWS_DATE` DATE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G4`.`DISCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G4`.`DISCOUNT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DISCOUNT_NAME` VARCHAR(45) NOT NULL,
  `DISCOUNT_CONTENT` VARCHAR(45) NOT NULL,
  `DISCOUNT_CODE` VARCHAR(45) NOT NULL,
  `DISCOUNT_DATE` DATE NOT NULL,
  `DISCOUNT_QRCODE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
